version: '2.1'
services:  
#raspberry pi camera (webpage)
  balena-cam:
    build:
      context:  ./balena-cam
      dockerfile: Dockerfile.armhf
    privileged: true
    restart: always
    network_mode: "host"
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0 
    labels:
      io.balena.features.kernel-modules: '1'
#USB video webcam's URL rtsp://<ip-address>:8554/webcam
  webcam:
    image: betothreeprod/webcam-stream:latest-ffmpeg-rpi
    build:
      context: .
      dockerfile: Dockerfile.armhf
#    sysctls:
#      - fs.protected_regular=0
    restart: "always"
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0 
    privileged: true
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      MTX_PATH: webcam
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    labels:
      io.balena.features.dbus: "1"
    network_mode: host
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    privileged: true
    volumes:
      - "openvc:/opt/vc"
volumes:
  openvc:
